spring:
  application:
    name: auth-jwt
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # 명백하게 명시만 해두면 안전하지만, 없어도 기본값이 SpringPhysicalNamingStrategy
        spring.jpa.hibernate.naming.physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        jdbc:
          time-zone: Asia/Seoul
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/auth_jwt?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: psw_auth
    password: auth1234!
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile,email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  jwt:
    secret: ${JWT_SECRET_KEY}
  data:
    redis:
      host: localhost
      port: 6379
      database: 1

logging:
  level:
    p6spy: DEBUG
    com.p6spy.engine.spy: DEBUG
    org.springframework.data.redis: DEBUG
    org.springframework.data.redis.connection: DEBUG
    org.springframework.data.redis.core: DEBUG

decorator:
  datasource:
    p6spy:
      enable-logging: true